### ISSUE TITLE
ul > li tags

### ISSUE THREAD

**Issue by berryny** [masu12/onepager#1]

**Comment by berryny** [comment]
```
<ul>Gigabit Harlem
Galvanize Community
Education
Innovation Center and Jobs
<li><a href="http://www.google.com">harlem</a></li>
</ul>
```
[Defines an unordered list](https://www.w3schools.com/tags/tag_ul.asp)

**Comment by masu12** [comment]
I see Judi...got it! I've just edited it, and I'll continue reviewing the info you suggested me to check. Thank you for looking into it.

**Comment by berryny** [comment]
> I see Judi...got it! I've just edited it, and I'll continue reviewing the info you suggested me to check. Thank you for looking into it.
